model_list:
  # Modelo Principal (OpenAI)
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      
  # Modelo Guardrail e Roteador Rápido (OpenAI GPT-4o-mini)
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  # Modelo Juiz (Trocado para gpt-4o-mini da OpenAI)
  - model_name: gemini-flash
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  drop_params: true

